SELECT
	EST_NF_ENT.CD_FILIAL 		AS FILIAL,
	NR_NF                    	AS NUMERO,
	SERIE 			AS SERIE,
	DT_EMI_NF 				AS EMISSAO,
	ISNULL(NR_AUTORIZADOR,'') 	AS CHAVE,
	CD_FORN 				AS CLIENTE
FROM 
	EST_NF_ENT
	INNER JOIN EST_NF_SERIE ON  
	EST_NF_ENT.CD_EMP = EST_NF_SERIE.CD_EMP 
	AND EST_NF_ENT.CD_NF_SERIE = EST_NF_SERIE.CD_NF_SERIE
	LEFT JOIN EST_NF_ENT_NFE ON
	EST_NF_ENT.CD_EMP = EST_NF_ENT_NFE.CD_EMP
	AND EST_NF_ENT.CD_NF = EST_NF_ENT_NFE.CD_NF
	AND EST_NF_ENT.CD_FILIAL = EST_NF_ENT_NFE.CD_FILIAL
WHERE 
	1 = 1
