SELECT 
	F.ZZ1_FILLIN 										AS FILIAL,
	F1_DOC 												AS NUMERO,
	F1_SERIE 												AS SERIE,
	CONVERT(DATE, F1_EMISSAO, 103) 	AS EMISSAO,
	F1_CHVNFE 											AS CHAVE,
	F1_FORNECE 										AS CLIENTE
FROM 
	SF1010 S
	INNER JOIN ZZ1010 F  ON S.F1_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''
	AND F.D_E_L_E_T_ = ''
	AND S.F1_ESPECIE = 'SPED'