SELECT
	EST_NF_ENT.CD_FILIAL 		AS FILIAL,
	EST_NF_ENT.CD_FILIAL 		AS FILIAL_TOTVS,
	NR_NF                    	AS NUMERO,
	SERIE 			AS SERIE,
	DT_EMI_NF 				AS EMISSAO,
	ISNULL(NR_AUTORIZADOR,'') 	AS CHAVE,
	CASE 
		WHEN STS_NF = 1 THEN 'CANCELADO'
		WHEN STS_NF = 3 THEN 'DENEGADA'
		ELSE 'ATIVO'
	END CANCELADO,
	CASE 
		WHEN GLB_MOV_OP.DEST_ORIG = 2 THEN 
			(Select 
					CD_FORN 
				From 
					PRC_FILIAL_PG_FORN 
				Where 
					CD_EMP = 1 
					AND CD_FILIAL = EST_NF_ENT.CD_FORN
			)
		ELSE CD_FORN
	END CLIENTE,
	VLR_NF AS VALOR
FROM 
	EST_NF_ENT
	INNER JOIN EST_NF_SERIE ON  
	EST_NF_ENT.CD_EMP = EST_NF_SERIE.CD_EMP 
	AND EST_NF_ENT.CD_NF_SERIE = EST_NF_SERIE.CD_NF_SERIE
	LEFT JOIN EST_NF_ENT_NFE ON
	EST_NF_ENT.CD_EMP = EST_NF_ENT_NFE.CD_EMP
	AND EST_NF_ENT.CD_NF = EST_NF_ENT_NFE.CD_NF
	AND EST_NF_ENT.CD_FILIAL = EST_NF_ENT_NFE.CD_FILIAL
	LEFT JOIN GLB_MOV_OP ON
	CD_NT_MOV = GLB_MOV_OP.CD_MOV_OP
WHERE 
	EST_NF_ENT.CD_EMP = 1
