SELECT 
	F.ZZ1_FILLIN 										AS FILIAL,
	S.F1_FILIAL	 										AS FILIAL_TOTVS,
	F1_DOC 												AS NUMERO,
	F1_SERIE 												AS SERIE,
	CONVERT(DATE, F1_EMISSAO, 103) 	AS EMISSAO,
	F1_CHVNFE 											AS CHAVE,
	F1_FORNECE 										AS CLIENTE,
	'ATIVO'													AS CANCELADO,
	F1_VALMERC										AS VALOR
FROM 
	SF1010 S
	INNER JOIN ZZ1010 F  ON S.F1_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''
	AND F.D_E_L_E_T_ = ''
	AND S.F1_ESPECIE = 'SPED'
	
UNION ALL

SELECT
	F.ZZ1_FILLIN 										AS FILIAL,
	S.F3_FILIAL 											AS FILIAL_TOTVS,
	F3_NFISCAL											AS NUMERO,
	F3_SERIE 												AS SERIE,
	CONVERT(DATE, F3_EMISSAO, 103) 	AS EMISSAO,
	F3_CHVNFE 											AS CHAVE,
	F3_CLIEFOR											AS CLIENTE,
	'CANCELADO' 											AS CANCELADO,
	F3_VALCONT											AS VALOR
FROM 
	SF3010 S
	INNER JOIN ZZ1010 F  ON S.F3_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''
	AND F.D_E_L_E_T_ = ''
	AND F3_ESPECIE = 'SPED'
	AND F3_OBSERV = 'NF CANCELADA' 
	AND CONVERT(INT, F3_CFO) < 5000