SELECT 
CD_FORN AS CODIGO,
RZ_FORN	 AS NOME,
CGC_CPF AS CGC_CPF,
INSC_EST AS INSC_EST,
CASE
		WHEN  F.PESSOA = 1
		THEN 'J'
		WHEN F.PESSOA = 0
		THEN 'F'
		ELSE 'X'
	END AS TIPO,
CASE	
		WHEN CID.UF = 'SN'  
		THEN 'MG'
		ELSE CID.UF
		END	AS UF
FROM PG_FORN F
INNER JOIN 
	V_GLB_CID_IPDV CID
	ON	F.CD_CID = CID.CD_CID
WHERE 
	F.STS_FORN = 0 