select
	EST_NF_SAI.CD_FILIAL 		AS FILIAL,
	NF_NF                    	AS NUMERO,
	SERIE 						AS SERIE,
	DT_EMI_NF 					AS EMISSAO,
	ISNULL(NR_AUTORIZADOR,'') 	AS CHAVE,
	CD_CLI 						AS CLIENTE
from EST_NF_SAI
	INNER JOIN EST_NF_SERIE ON  
	EST_NF_SAI.CD_EMP = EST_NF_SERIE.CD_EMP 
	AND EST_NF_SAI.CD_NF_SERIE = EST_NF_SERIE.CD_NF_SERIE
	LEFT JOIN EST_NF_SAI_NFE ON
	EST_NF_SAI.CD_EMP = EST_NF_SAI_NFE.CD_EMP
	AND EST_NF_SAI.CD_NF = EST_NF_SAI_NFE.CD_NF
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_NFE.CD_FILIAL
where 
	dt_cancel is null 