SELECT
	EST_NF_SAI.CD_FILIAL 		AS FILIAL,
	NF_NF                    				AS TITULO,
	CD_CLI									AS CODFORN,
	RZ_DESTINATARIO				AS NMFORN,
	DT_EMI_NF 							AS DT_EMISSAO,
	DT_EMI_NF 							AS DT_VENCIMENTO,
	NF_NF                    				AS NUMERO,
	VLR_NF 								AS VALOR,
	OBS1  									AS HISTORICO,
	OBS2  									AS OBS2, 
	OBS3									AS OBS3,
	EST_NF_SAI.CD_FILIAL 		AS FILIAL_TOTVS,
	CASE 
		WHEN STS_NF = 1 
			AND EST_NF_SAI_EST_NF_NFE_INU.CD_INU IS NULL 
			AND EST_NF_SAI_CANCEL.CANCEL_FORA_PRAZO <> 1 
			THEN 'CANCELADO'
		WHEN EST_NF_SAI_EST_NF_NFE_INU.CD_INU IS NOT NULL  THEN 'INUTILIZADO'
		WHEN EST_NF_SAI_CANCEL.CANCEL_FORA_PRAZO = 1  THEN 'EXTEMPORÂNEO'
		WHEN STS_NF = 3 THEN 'DENEGADA'
		ELSE 'ATIVO'
	END CANCELADO
FROM EST_NF_SAI
	LEFT OUTER JOIN EST_NF_SAI_EST_NF_NFE_INU ON  
	EST_NF_SAI.CD_EMP = EST_NF_SAI_EST_NF_NFE_INU.CD_EMP  
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_EST_NF_NFE_INU.CD_FILIAL  
    AND EST_NF_SAI.CD_NF = EST_NF_SAI_EST_NF_NFE_INU.CD_NF
	LEFT OUTER JOIN EST_NF_SAI_CANCEL ON 
	EST_NF_SAI.CD_EMP = EST_NF_SAI_CANCEL.CD_EMP
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_CANCEL.CD_FILIAL
	AND EST_NF_SAI.CD_NF = EST_NF_SAI_CANCEL.CD_NF
WHERE 
	CD_NT_MOV IN (6)
