SELECT
	EST_NF_SAI.CD_FILIAL 		AS FILIAL,
	EST_NF_SAI.CD_FILIAL 		AS FILIAL_TOTVS,
	NF_NF                    	AS NUMERO,
	SERIE 						AS SERIE,
	DT_EMI_NF 					AS EMISSAO,
	ISNULL(EST_NF_SAI_NFE.NR_AUTORIZADOR,'') 	AS CHAVE,
	CD_CLI 						AS CLIENTE,
	CASE 
		WHEN STS_NF = 1 
			AND EST_NF_SAI_EST_NF_NFE_INU.CD_INU IS NULL 
			AND EST_NF_SAI_CANCEL.CANCEL_FORA_PRAZO <> 1 
			THEN 'CANCELADO'
		WHEN EST_NF_SAI_EST_NF_NFE_INU.CD_INU IS NOT NULL  THEN 'INUTILIZADO'
		WHEN EST_NF_SAI_CANCEL.CANCEL_FORA_PRAZO = 1  THEN 'EXTEMPORÂNEO'
		WHEN STS_NF = 3 THEN 'DENEGADA'
		ELSE 'ATIVO'
	END CANCELADO
FROM EST_NF_SAI
	INNER JOIN EST_NF_SERIE ON  
	EST_NF_SAI.CD_EMP = EST_NF_SERIE.CD_EMP 
	AND EST_NF_SAI.CD_NF_SERIE = EST_NF_SERIE.CD_NF_SERIE
	LEFT JOIN EST_NF_SAI_NFE ON
	EST_NF_SAI.CD_EMP = EST_NF_SAI_NFE.CD_EMP
	AND EST_NF_SAI.CD_NF = EST_NF_SAI_NFE.CD_NF
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_NFE.CD_FILIAL
	LEFT OUTER JOIN EST_NF_SAI_EST_NF_NFE_INU ON  
	EST_NF_SAI.CD_EMP = EST_NF_SAI_EST_NF_NFE_INU.CD_EMP  
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_EST_NF_NFE_INU.CD_FILIAL  
    AND EST_NF_SAI.CD_NF = EST_NF_SAI_EST_NF_NFE_INU.CD_NF
	LEFT OUTER JOIN EST_NF_SAI_CANCEL ON 
	EST_NF_SAI.CD_EMP = EST_NF_SAI_CANCEL.CD_EMP
	AND EST_NF_SAI.CD_FILIAL = EST_NF_SAI_CANCEL.CD_FILIAL
	AND EST_NF_SAI.CD_NF = EST_NF_SAI_CANCEL.CD_NF
where 
	EST_NF_SAI.CD_EMP = 1