SELECT 
	RC_DEB.CD_FILIAL									AS FILIAL,
	RC_DEB.NR_DP										AS NUMERO,
	CG_FND_VERBA_RC_DEB_DUP_NR_CTR.CD_FND_VERBA			AS CONTROLE,
	RC_DEB.DT_DP										AS EMISSAO,
	RC_DEB.DT_VENCTO									AS VENCIMENTO,
	DATEDIFF(d, RC_DEB.DT_VENCTO, GETDATE())			AS ATRASO,
	RC_DEB.CD_CLI										AS CODCLIENTE,
	RC_CLI.NM_FANT										AS NOME,
	RC_DEB.VLR_DP										AS VALOR,
	RC_DEB.SLD_DP										AS SALDO,
	CASE 
		RC_DEB.STS_DP
           WHEN 0 THEN CASE RC_DEB.STS_NF
                           WHEN 0 THEN 'EM ABERTO'
                           ELSE 'NOTA FISCAL CANCELADA'
                       END
           WHEN 1 THEN 'QUITADA'
           WHEN 2 THEN 'PGTO PARCIAL'
           WHEN 3 THEN 'CANCELADA'
           WHEN 4 THEN 'RENEGOCIADA'
           WHEN 5 THEN 'AGUARDANDO RETORNO BANCO (CNAB)'
           WHEN 6 THEN 'DUPLICATA DE CREDIARIO ESTORNADA'
           ELSE 'NÃO DEFINIDO'
       END												AS STS_DP
FROM 
	RC_DEB
	INNER JOIN RC_CLI 
		ON RC_DEB.CD_EMP = RC_CLI.CD_EMP
		AND RC_DEB.CD_CLI = RC_CLI.CD_CLI
	INNER JOIN CG_FND_VERBA_RC_DEB_DUP_NR_CTR 
		ON RC_DEB.CD_EMP = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.CD_EMP
		AND RC_DEB.CD_FILIAL = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.CD_FILIAL
		AND RC_DEB.NR_DP = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.NR_DP
		AND RC_DEB.ANO = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.ANO
WHERE 
	RC_DEB.CD_EMP =1
	/*AND NOT EXISTS
		(SELECT 1
			FROM PRC_FILIAL_RC_CLI
			WHERE RC_CLI.CD_EMP = PRC_FILIAL_RC_CLI.CD_EMP
				AND RC_CLI.CD_CLI = PRC_FILIAL_RC_CLI.CD_CLI)*/
				
	--AND RC_DEB.DT_DP BETWEEN '20230620' AND '20230620'
	
	