SELECT 
	PDV_VD.CD_FILIAL 				AS FILIAL, 
	PDV_VD.CD_FILIAL 				AS FILIAL_TOTVS, 
	PDV_VD.NR_ECF 					AS NUMERO,
	PDV_VD.CD_CX 					AS SERIE,   
	PDV_VD.DT_VD 					AS EMISSAO, 
	PDV_VD.CHV_NFCE 				AS CHAVE,
	PDV_VD.CD_CLI 					AS CLIENTE,
	'ATIVO' 								AS CANCELADO,
	PDV_VD.VLR_VD					AS VALOR
FROM 
	PDV_VD 
WHERE 
	PDV_VD.CD_EMP = 1
	AND ST_VD = 0
	
UNION ALL 

SELECT 
	PDV_VD.CD_FILIAL 				AS FILIAL, 
	PDV_VD.CD_FILIAL 				AS FILIAL_TOTVS, 
	PDV_VD.NR_ECF 					AS NUMERO,
	PDV_VD.CD_CX 					AS SERIE,   
	PDV_VD.DT_VD 					AS EMISSAO, 
	PDV_VD.CHV_NFCE 				AS CHAVE,
	PDV_VD.CD_CLI 					AS CLIENTE,
	'CANCELADO' 						AS CANCELADO,
	PDV_VD.VLR_VD					AS VALOR
FROM PDV_VD
	INNER JOIN PDV_VD_PDV_VD_NFCE ON PDV_VD.CD_EMP = PDV_VD_PDV_VD_NFCE.CD_EMP
	AND PDV_VD.CD_FILIAL = PDV_VD_PDV_VD_NFCE.CD_FILIAL
	AND PDV_VD.CD_VD = PDV_VD_PDV_VD_NFCE.CD_VD
	INNER JOIN PDV_VD_NFCE ON PDV_VD_PDV_VD_NFCE.CD_NFCE = PDV_VD_NFCE.CD_NFCE
	LEFT JOIN PDV_VD_NFCE_CANCEL ON PDV_VD_NFCE_CANCEL.CD_NFCE = PDV_VD_NFCE.CD_NFCE
WHERE 
	PDV_VD.CD_EMP =1
	AND PDV_VD.FLAG_NFCE =1
	AND PDV_VD.ST_VD =1
	AND ISNULL(PDV_VD_NFCE_CANCEL.TP_EMIS, 0) = 0