SELECT 
	F.ZZ1_FILLIN 										AS FILIAL,
	S.F2_FILIAL 											AS FILIAL_TOTVS,
	F2_DOC 												AS NUMERO,
	F2_SERIE 												AS SERIE,
	CONVERT(DATE, F2_EMISSAO, 103) 	AS EMISSAO,
	F2_CHVNFE 											AS CHAVE,
	F2_CLIENTE 											AS CLIENTE,
	'ATIVO' 												AS CANCELADO
FROM 
	SF2010 S
	INNER JOIN ZZ1010 F  ON S.F2_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''  
	AND F.D_E_L_E_T_ = ''
	AND F2_ESPECIE = 'NFCE'
	
UNION ALL

SELECT
	F.ZZ1_FILLIN 										AS FILIAL,
	S.F3_FILIAL 											AS FILIAL_TOTVS,
	F3_NFISCAL											AS NUMERO,
	F3_SERIE 												AS SERIE,
	CONVERT(DATE, F3_EMISSAO, 103) 	AS EMISSAO,
	F3_CHVNFE 											AS CHAVE,
	F3_CLIEFOR											AS CLIENTE,
	'CANCELADO' 										AS CANCELADO
FROM 
	SF3010 S
	INNER JOIN ZZ1010 F  ON S.F3_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''
	AND F.D_E_L_E_T_ = ''
	AND F3_ESPECIE = 'NFCE'
	AND F3_OBSERV = 'NF CANCELADA' 