SELECT 
	F.ZZ1_FILLIN 										AS FILIAL,
	F2_DOC 												AS NUMERO,
	F2_SERIE 												AS SERIE,
	CONVERT(DATE, F2_EMISSAO, 103) 	AS EMISSAO,
	F2_CHVNFE 											AS CHAVE,
	F2_CLIENTE 										AS CLIENTE
FROM 
	SF2010 S
	INNER JOIN ZZ1010 F  ON S.F2_FILIAL = F.ZZ1_FILPRO 
WHERE 
	S.D_E_L_E_T_ = ''  
	AND F.D_E_L_E_T_ = ''
	AND F2_ESPECIE = 'NFCE'