SELECT
	P.CD_PROD			AS CODIGO,
	P.DS_PROD			AS DESCRICAO,
	P.NR_NCM				AS NCM,
	B.CD_BARRA			AS BARRAS,		
	CASE
		WHEN  P.STS_PROD = 1
		THEN 'INATIVO'
		WHEN P.STS_PROD = 0
		THEN 'ATIVO'
		ELSE 'BLOQUEADO'
	END 						AS ATIVO
FROM
	EST_PROD P
	
CROSS APPLY (
	SELECT TOP 1
		CD_BARRA
	FROM
		EST_PROD_CD_BARRA C
	WHERE P.CD_EMP = C.CD_EMP
			AND P.CD_PROD = C.CD_PROD
			AND C.FLAG_PRE_VENCIDOS <> 1
			AND C.NAO_USAR_PED_ELETR = 0
			AND C.EAN_CAIXA_FECHADA = 0
			AND C.NAO_EXPORTAR = 0
) B
WHERE
	1 = 1