/* ESTOU AGRUPANDO OS VALORES DE PARCELAMENTO PARA TER SOMENTE UMA LINHA DO CARTÃO */
SELECT 
	PDV_VD.CD_FILIAL																																	 AS FILIAL, 
	CONCAT(
		RIGHT('0' + CONVERT(VARCHAR(MAX), PDV_VD.CD_CX), 2),
		PDV_VD.NR_ECF)																																AS NUMERO,
	RC_ADM_CARTAO_RC_CLI.CD_CLI																												AS CODCLIENTE,
	PDV_VD.DT_VD																																		AS EMISSAO, 
	SUM(PDV_VD_TEF.VL_CARTAO)																													AS VALOR,
	/*CONVERT(DECIMAL(12,2),
		(CASE
           WHEN RC_ADM_CARTAO.PARC <= 1 THEN PDV_VD_TEF.VL_CARTAO / 1
           ELSE (CAST(PDV_VD_TEF.VL_CARTAO AS DECIMAL(18, 12))) / (CAST(RC_ADM_CARTAO.PARC AS DECIMAL(18, 12)))
		END))																					AS VALOR,	*/
	CASE
		WHEN RC_ADM_CARTAO.TP_ADM IN(0,2)	THEN 'CC'
	    WHEN RC_ADM_CARTAO.TP_ADM IN(1,3)	THEN 'CD'
		WHEN RC_ADM_CARTAO.TP_ADM = 7		THEN 'PIX'
	END																																						AS TIPO,
	RC_CLI.NM_FANT																																	AS NOME_OPERADORA,
	ISNULL(PDV_VD.OBS,'')																COLLATE SQL_Latin1_General_CP1_CI_AS AS OBS
FROM
	PDV_VD
	INNER JOIN PDV_VD_TEF 
		ON PDV_VD.CD_EMP = PDV_VD_TEF.CD_EMP
		AND	PDV_VD.CD_FILIAL = PDV_VD_TEF.CD_FILIAL
		AND	PDV_VD.CD_VD = PDV_VD_TEF.CD_VD
	INNER JOIN RC_ADM_CARTAO 
		ON PDV_VD_TEF.CD_EMP = RC_ADM_CARTAO.CD_EMP
		AND PDV_VD_TEF.CD_ADM_CARTAO = RC_ADM_CARTAO.CD_ADM_CARTAO
	LEFT JOIN RC_ADM_CARTAO_RC_CLI	
		ON PDV_VD_TEF.CD_EMP = RC_ADM_CARTAO_RC_CLI.CD_EMP
		AND	PDV_VD_TEF.CD_ADM_CARTAO = RC_ADM_CARTAO_RC_CLI.CD_ADM_CARTAO
	/*LEFT OUTER JOIN RC_ADM_CARTAO_VENCTO 
		ON RC_ADM_CARTAO.CD_EMP = RC_ADM_CARTAO_VENCTO.CD_EMP
		AND RC_ADM_CARTAO.CD_ADM_CARTAO = RC_ADM_CARTAO_VENCTO.CD_ADM_CARTAO*/
	LEFT JOIN RC_CLI 
		ON RC_ADM_CARTAO_RC_CLI.CD_EMP = RC_CLI.CD_EMP
		AND	RC_ADM_CARTAO_RC_CLI.CD_CLI = RC_CLI.CD_CLI
WHERE 
	PDV_VD.CD_EMP = 1
	AND PDV_VD_TEF.CD_ADM_CARTAO <> 183
	--AND PDV_VD.DT_VD BETWEEN '2023-06-20' AND '2023-06-20'
	--AND PDV_VD.CD_FILIAL = 10
	
GROUP BY 
	PDV_VD.CD_FILIAL,
	PDV_VD.CD_CX,
	PDV_VD.NR_ECF,
	RC_ADM_CARTAO_RC_CLI.CD_CLI,
	PDV_VD.DT_VD,
	CASE
		WHEN RC_ADM_CARTAO.TP_ADM IN(0,2)	THEN 'CC'
	    WHEN RC_ADM_CARTAO.TP_ADM IN(1,3)	THEN 'CD'
		WHEN RC_ADM_CARTAO.TP_ADM = 7		THEN 'PIX'
	END	,
	RC_CLI.NM_FANT,
	PDV_VD.OBS
	
	
UNION ALL

SELECT 
	PDV_CUPOM_NAO_FISCAL.CD_FILIAL																																	AS FILIAL,
	CONCAT(
		RIGHT('0' + CONVERT(VARCHAR(MAX), PDV_CUPOM_NAO_FISCAL.CD_CX), 2),
		PDV_CUPOM_NAO_FISCAL.NR_COO)																																AS NUMERO,
	RC_ADM_CARTAO_RC_CLI.CD_CLI																																		AS CODCLIENTE,
	PDV_CUPOM_NAO_FISCAL.DT_CUPOM	 																															AS EMISSAO,
	PDV_VD_TEF.VL_CARTAO																																					AS VALOR,
	CASE
		WHEN RC_ADM_CARTAO.TP_ADM IN(0,2)	THEN 'CC'
	    WHEN RC_ADM_CARTAO.TP_ADM IN(1,3)	THEN 'CD'
		WHEN RC_ADM_CARTAO.TP_ADM = 7		THEN 'PIX'
	END																																												AS TIPO,
	RC_CLI.NM_FANT																																							AS NOME_OPERADORA,
	ISNULL(PDV_VD_TEF.OBS,'')																				COLLATE SQL_Latin1_General_CP1_CI_AS AS OBS
FROM 
	PDV_CUPOM_NAO_FISCAL
	INNER JOIN PDV_CUPOM_NAO_FISCAL_TEF	
		ON PDV_CUPOM_NAO_FISCAL.CD_EMP = PDV_CUPOM_NAO_FISCAL_TEF.CD_EMP
		AND	PDV_CUPOM_NAO_FISCAL.CD_FILIAL = PDV_CUPOM_NAO_FISCAL_TEF.CD_FILIAL
		AND	PDV_CUPOM_NAO_FISCAL.CD_CTR = PDV_CUPOM_NAO_FISCAL_TEF.CD_CTR
	INNER JOIN PDV_RECBTO_TEF AS PDV_VD_TEF	
		ON PDV_VD_TEF.CD_EMP = PDV_CUPOM_NAO_FISCAL_TEF.CD_EMP
		AND	PDV_VD_TEF.CD_FILIAL = PDV_CUPOM_NAO_FISCAL_TEF.CD_FILIAL
		AND	PDV_VD_TEF.CD_RECTO_TEF = PDV_CUPOM_NAO_FISCAL_TEF.CD_RECTO_TEF
	LEFT JOIN RC_ADM_CARTAO_RC_CLI	
		ON PDV_VD_TEF.CD_EMP = RC_ADM_CARTAO_RC_CLI.CD_EMP
		AND	PDV_VD_TEF.CD_ADM_CARTAO = RC_ADM_CARTAO_RC_CLI.CD_ADM_CARTAO
	INNER JOIN RC_ADM_CARTAO ON RC_ADM_CARTAO_RC_CLI.CD_EMP = RC_ADM_CARTAO.CD_EMP
		AND RC_ADM_CARTAO_RC_CLI.CD_ADM_CARTAO = RC_ADM_CARTAO.CD_ADM_CARTAO
	LEFT JOIN RC_CLI 
		ON RC_ADM_CARTAO_RC_CLI.CD_EMP = RC_CLI.CD_EMP
		AND	RC_ADM_CARTAO_RC_CLI.CD_CLI = RC_CLI.CD_CLI
WHERE 
	PDV_CUPOM_NAO_FISCAL.CD_EMP = 1
	
	--AND PDV_CUPOM_NAO_FISCAL.DT_CUPOM BETWEEN '2015-06-20' AND '2023-06-20'
	--AND PDV_CUPOM_NAO_FISCAL.CD_FILIAL = 27
	
	