SELECT 
       RC_DEB.CD_FILIAL																	AS FILIAL,
       RC_DEB.NR_DP																		AS NUMERO,
	   RC_DEB.CD_CLI																	AS CODCLIENTE,
	   RC_CLI.RZ_CLI																	AS NOME,
	   RC_DEB.VLR_DP																	AS VALOR,
       RC_DEB.DT_DP																		AS EMISSAO,
       RC_DEB.DT_VENCTO																	AS VENCIMENTO,
	   ISNULL(Q.DT_PGTO,'1900-01-01')																	AS DT_BAIXA,
	   ISNULL(Q.VLR_PAGO,0)																AS VALOR_BAIXA
	   --ISNULL(Q_HIST.DT_PAG,0) 															AS DT_BAIXA,
	   --ISNULL(Q_HIST.VL_PGTO,0)															AS VALOR_BAIXA
FROM 
	RC_DEB
	INNER JOIN RC_CLI 
		ON RC_DEB.CD_EMP = RC_CLI.CD_EMP 
		AND RC_DEB.CD_CLI = RC_CLI.CD_CLI
	INNER JOIN RC_CREDIARIO_FECHA_RC_DEB 
		ON RC_DEB.CD_EMP=RC_CREDIARIO_FECHA_RC_DEB.CD_EMP 
		AND RC_DEB.CD_FILIAL=RC_CREDIARIO_FECHA_RC_DEB.CD_FILIAL 
		AND RC_DEB.CD_RC_DEB = RC_CREDIARIO_FECHA_RC_DEB.CD_RC_DEB
	LEFT JOIN V_QUITACOES Q
		ON Q.NR_FATURA = CONCAT(YEAR(RC_DEB.DT_DP), '-', RC_DEB.CD_FILIAL, '-', RC_DEB.NR_DP, '-', RC_DEB.PARC)
	/*LEFT JOIN V_RC_CRED_HIST Q_HIST
		ON Q_HIST.CD_EMP = RC_DEB.CD_EMP 
		AND Q_HIST.CD_FILIAL = RC_DEB.CD_FILIAL 
		AND Q_HIST.CD_RC_DEB = RC_DEB.CD_RC_DEB*/
WHERE 
	RC_DEB.CD_EMP = 1
	AND NOT EXISTS
		(SELECT 1
			FROM PRC_FILIAL_RC_CLI
			WHERE RC_CLI.CD_EMP = PRC_FILIAL_RC_CLI.CD_EMP
			AND RC_CLI.CD_CLI = PRC_FILIAL_RC_CLI.CD_CLI)
	--AND RC_DEB.DT_DP BETWEEN '2023-02-25' AND '2023-02-25'
	--and Q_HIST.DT_PAG BETWEEN '2023-04-29' AND '2023-06-29'
	--AND RC_DEB.NR_DP = 23000350

	


