SELECT 
       RC_DEB.CD_FILIAL																										AS FILIAL,
       RC_DEB.NR_DP																											AS NUMERO,
	   RC_DEB.PARC																											AS PARCELA,
	   RC_DEB.CD_CLI																										AS CODCLIENTE,
	   RC_CLI.RZ_CLI																										AS NOME,
       COALESCE(RC_DEB_NF.VLR_NF, RC_DEB.VLR_DP)																			AS VALOR,
       ISNULL(COALESCE(Q.VLR_PAGO ,((V_RC_DEB_VLR_PGTO.VLR_PGTO + V_RC_DEB_VLR_PGTO.VL_JUR - (V_RC_DEB_VLR_PGTO.VL_DESC + 
							V_RC_DEB_VLR_PGTO.VLR_GLOSA + V_RC_DEB_VLR_PGTO.VLR_IMP)))),0)				AS SALDO,
	   ISNULL(Q.DT_PGTO,' ')																					AS BAIXA, 
       RC_DEB.DT_DP																															AS EMISSAO,
       RC_DEB.DT_VENCTO																													AS VENCIMENTO,
	   ISNULL(NR_COO, 0) AS CUPOM,
	   ISNULL(CD_CX,0) AS CAIXA
      
FROM RC_DEB
INNER JOIN 
	RC_CLI 
		ON RC_DEB.CD_EMP = RC_CLI.CD_EMP AND RC_DEB.CD_CLI = RC_CLI.CD_CLI
LEFT JOIN 
	RC_DEB_RC_DEB_NEGOCIACAO Rn 
		ON RC_DEB.CD_EMP = Rn.CD_EMP 
			AND RC_DEB.CD_FILIAL = Rn.CD_FILIAL AND RC_DEB.CD_RC_DEB = Rn.CD_RC_DEB
INNER JOIN 
	RC_CLI_CREDIARIO 
		ON RC_CLI_CREDIARIO.CD_EMP=RC_CLI.CD_EMP 
			AND RC_CLI_CREDIARIO.CD_CLI = RC_CLI.CD_CLI
INNER JOIN 
	RC_CREDIARIO_FECHA_RC_DEB 
		ON RC_DEB.CD_EMP=RC_CREDIARIO_FECHA_RC_DEB.CD_EMP 
			AND RC_DEB.CD_FILIAL=RC_CREDIARIO_FECHA_RC_DEB.CD_FILIAL AND RC_DEB.Cd_Rc_Deb = RC_CREDIARIO_FECHA_RC_DEB.Cd_Rc_Deb
LEFT OUTER JOIN 
	BC_BANCO 
		ON BC_BANCO.CD_EMP = RC_DEB.CD_EMP 
			AND BC_BANCO.CD_BC = RC_DEB.CD_BC
LEFT OUTER JOIN 
	V_RC_DEB_IMPOSTO 
		ON RC_DEB.CD_EMP = V_RC_DEB_IMPOSTO.CD_EMP 
			AND RC_DEB.CD_FILIAL = V_RC_DEB_IMPOSTO.CD_FILIAL AND RC_DEB.CD_RC_DEB = V_RC_DEB_IMPOSTO.CD_RC_DEB
LEFT OUTER JOIN 
	V_RC_DEB_VLR_PGTO 
		ON RC_DEB.CD_EMP = V_RC_DEB_VLR_PGTO.CD_EMP 
			AND RC_DEB.CD_FILIAL = V_RC_DEB_VLR_PGTO.CD_FILIAL AND RC_DEB.CD_RC_DEB = V_RC_DEB_VLR_PGTO.CD_RC_DEB
INNER JOIN 
	PRC_GRP_ECON_PRC_FILIAL 
		ON RC_DEB.CD_EMP = PRC_GRP_ECON_PRC_FILIAL.CD_EMP 
			AND RC_DEB.CD_FILIAL = PRC_GRP_ECON_PRC_FILIAL.CD_FILIAL
INNER JOIN 
	PRC_GRP_ECON 
		ON PRC_GRP_ECON_PRC_FILIAL.CD_GRP_ECON = PRC_GRP_ECON.CD_GRP_ECON
LEFT OUTER JOIN
	(SELECT DISTINCT CD_EMP,
                   CD_CLI
		FROM RC_CLI_CONV_VINC_RC_CLI) RC_CLI_CONV_VINC_RC_CLI 
					ON RC_DEB.CD_EMP = RC_CLI_CONV_VINC_RC_CLI.CD_EMP AND RC_DEB.CD_CLI = RC_CLI_CONV_VINC_RC_CLI.CD_CLI
LEFT OUTER JOIN
	(SELECT DISTINCT CD_EMP,
                   CD_CLI
		FROM RC_ADM_CARTAO_RC_CLI CLI)RC_ADM_CARTAO_RC_CLI 
					ON RC_CLI.CD_EMP = RC_ADM_CARTAO_RC_CLI.CD_EMP AND RC_CLI.CD_CLI = RC_ADM_CARTAO_RC_CLI.CD_CLI
LEFT OUTER JOIN 
	CG_FND_VERBA_RC_DEB_DUP_NR_CTR 
		ON RC_DEB.CD_EMP = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.CD_EMP AND RC_DEB.CD_FILIAL = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.CD_FILIAL AND RC_DEB.NR_DP = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.NR_DP AND RC_DEB.ANO = CG_FND_VERBA_RC_DEB_DUP_NR_CTR.ANO
LEFT JOIN 
	GLB_REG 
		ON GLB_REG.CD_EMP = RC_CLI.CD_EMP AND GLB_REG.CD_REG=RC_CLI.CD_REGI
INNER JOIN 
	CTB_HIST 
		ON CTB_HIST.CD_EMP = RC_DEB.CD_EMP AND CTB_HIST.Cd_Hist = RC_DEB.Cd_Hist
LEFT JOIN 
	RC_DEB_NOSSO_NUMERO RC_ARQ_REM_RET_CONTROLE 
		ON RC_DEB.cd_emp = RC_ARQ_REM_RET_CONTROLE.CD_EMP AND RC_DEB.CD_FILIAL = RC_ARQ_REM_RET_CONTROLE.CD_FILIAL AND RC_DEB.CD_RC_DEB = RC_ARQ_REM_RET_CONTROLE.CD_RC_DEB
LEFT JOIN 
	RC_DEB_NF
		ON RC_DEB_NF.CD_EMP=RC_DEB.CD_EMP AND RC_DEB_NF.CD_FILIAL=RC_DEB.CD_FILIAL AND RC_DEB_NF.NR_DP = RC_DEB.NR_DP

LEFT JOIN V_QUITACOES Q
	ON Q.NR_FATURA = CONCAT(YEAR(RC_DEB.DT_DP), '-', RC_DEB.CD_FILIAL, '-', RC_DEB.NR_DP, '-', RC_DEB.PARC)

WHERE 
		RC_DEB.CD_EMP = 1
  AND NOT EXISTS
    (SELECT *
     FROM PRC_FILIAL_RC_CLI
     WHERE RC_CLI.CD_EMP = PRC_FILIAL_RC_CLI.CD_EMP
       AND RC_CLI.CD_CLI = PRC_FILIAL_RC_CLI.CD_CLI)
  

GROUP BY RC_DEB.CD_EMP,
         RC_DEB.CD_FILIAL,
         RC_DEB.NR_DP,
         RC_DEB.PARC,
         RC_DEB.CD_CLI,
         RC_CLI.RZ_CLI,
         RC_DEB.VLR_DP,
         RC_DEB.SLD_DP,
		 Q.VLR_PAGO,
         V_RC_DEB_VLR_PGTO.VL_JUR,
         V_RC_DEB_VLR_PGTO.VL_DESC,
         RC_DEB.VLR_DESC,
         V_RC_DEB_VLR_PGTO.VLR_GLOSA,
         V_RC_DEB_IMPOSTO.VLR_IMP,
         V_RC_DEB_VLR_PGTO.VLR_PGTO,
         V_RC_DEB_VLR_PGTO.VLR_PGTO,
         V_RC_DEB_VLR_PGTO.VL_JUR,
         V_RC_DEB_VLR_PGTO.VL_DESC,
         V_RC_DEB_VLR_PGTO.VLR_GLOSA,
         V_RC_DEB_VLR_PGTO.VLR_IMP,
         RC_DEB.DT_DP,
         RC_DEB.DT_VENCTO,
         RC_DEB.STS_DP,
         RC_DEB.STS_NF,
         RC_CLI.TEL,
         RC_DEB.CD_BC,
         BC_BANCO.DS_BC,
         RC_CLI_CONV_VINC_RC_CLI.CD_CLI,
         PRC_GRP_ECON.NM_GRP_ECON,
         CG_FND_VERBA_RC_DEB_DUP_NR_CTR.NR_DP,
         RC_CLI.CD_FILIAL,
         GLB_REG.DS_REG,
         RC_DEB.CD_HIST,
         RC_DEB.HIST,
         CTB_HIST.DS_HIST,
         RC_DEB.ANO,
         RC_DEB.Cd_Rc_Deb,
         RC_ADM_CARTAO_RC_CLI.CD_CLI,
         RC_DEB_NF.NR_NF,
         RC_DEB_NF.VLR_NF,
		 Q.DT_PGTO,
		 NR_COO,
		 CD_CX


UNION ALL

SELECT 
       PDV_CUPOM_NAO_FISCAL.CD_FILIAL																													AS FILIAL,	
       PDV_CUPOM_NAO_FISCAL.CD_CTR																														AS NUMERO,		
	   RC_CREDIARIO_PARC.PARC_CRED																														AS PARCELA,
       RC_CLI.CD_CLI																																	AS CODCLIENTE,	
	   RC_CLI.RZ_CLI																										AS NOME,
	   RC_CREDIARIO_PARC_CRED.VLR_CRED																													AS VALOR,
       CASE																																				
           WHEN PDV_CUPOM_NAO_FISCAL.ST_CUPOM = 3 THEN PDV_CUPOM_NAO_FISCAL.VLR_TOT_CUPOM																
           ELSE RC_CREDIARIO_PARC_CRED.VLR_CRED																												
       END																																				AS SALDO,
	   ' '																																				AS BAIXA,
       DT_LANC_CRED																													AS EMISSAO,	
       DT_FECHA_CRED																												AS VENCIMENTO,
	   PDV_CUPOM_NAO_FISCAL.NR_COO 		AS CUPOM,
	   PDV_CUPOM_NAO_FISCAL.CD_CX 		AS CAIXA
FROM RC_CREDIARIO_PARC_CRED
INNER JOIN RC_PGTO_PDV_RC_CREDIARIO_PARC_CRED ON RC_CREDIARIO_PARC_CRED.CD_CTR = RC_PGTO_PDV_RC_CREDIARIO_PARC_CRED.CD_CTR
												AND RC_CREDIARIO_PARC_CRED.CD_CTR_CRED = RC_PGTO_PDV_RC_CREDIARIO_PARC_CRED.CD_CTR_CRED
INNER JOIN RC_CREDIARIO_PARC ON RC_CREDIARIO_PARC_CRED.CD_CTR = RC_CREDIARIO_PARC.CD_CTR
INNER JOIN RC_CLI ON RC_CREDIARIO_PARC.CD_EMP = RC_CLI.CD_EMP
												AND RC_CREDIARIO_PARC.CD_CLI = RC_CLI.CD_CLI
INNER JOIN GLB_CID ON RC_CLI.CD_CID = GLB_CID.CD_CID
LEFT OUTER JOIN RC_CLI_CREDIARIO ON RC_CLI.CD_EMP = RC_CLI_CREDIARIO.CD_EMP
												AND RC_CLI.CD_CLI = RC_CLI_CREDIARIO.CD_CLI
INNER JOIN RC_PGTO_PDV ON RC_PGTO_PDV_RC_CREDIARIO_PARC_CRED.CD_CTR_PGTO = RC_PGTO_PDV.CD_CTR_PGTO
INNER JOIN PDV_CUPOM_NAO_FISCAL
INNER JOIN PDV_CUPOM_NAO_FISCAL_RC_PGTO_PDV ON PDV_CUPOM_NAO_FISCAL.CD_EMP = PDV_CUPOM_NAO_FISCAL_RC_PGTO_PDV.CD_EMP
												AND PDV_CUPOM_NAO_FISCAL.CD_FILIAL = PDV_CUPOM_NAO_FISCAL_RC_PGTO_PDV.CD_FILIAL
												AND PDV_CUPOM_NAO_FISCAL.CD_CTR = PDV_CUPOM_NAO_FISCAL_RC_PGTO_PDV.CD_CTR ON RC_PGTO_PDV.CD_CTR_PGTO = PDV_CUPOM_NAO_FISCAL_RC_PGTO_PDV.CD_CTR_PGTO
LEFT OUTER JOIN RC_MOT_BLOQ_CLI ON RC_CLI_CREDIARIO.CD_MOT_BLOQ_CLI = RC_MOT_BLOQ_CLI.CD_MOT_BLOQ_CLI
INNER JOIN PRC_GRP_ECON_PRC_FILIAL ON PDV_CUPOM_NAO_FISCAL.CD_EMP = PRC_GRP_ECON_PRC_FILIAL.CD_EMP
												AND PDV_CUPOM_NAO_FISCAL.CD_FILIAL = PRC_GRP_ECON_PRC_FILIAL.CD_FILIAL
INNER JOIN PRC_GRP_ECON ON PRC_GRP_ECON_PRC_FILIAL.CD_GRP_ECON = PRC_GRP_ECON.CD_GRP_ECON
LEFT JOIN GLB_REG ON GLB_REG.CD_EMP = RC_CLI.CD_EMP
												AND GLB_REG.CD_REG=RC_CLI.CD_REGI

WHERE PDV_CUPOM_NAO_FISCAL.CD_EMP = 1
  AND PDV_CUPOM_NAO_FISCAL.ST_CUPOM <> 3